- name: install jitsi server
  hosts: server
  gather_facts: true
  tasks:
    - name: run jitsi server setup script
      shell:  /usr/local/dos-mitigation/common/setup/jitsi_server_setup.sh {{ server_name }}
      become: no

- name: install jitsi client
  hosts: client
  gather_facts: true
  tasks:
    - name: run jitsi client setup script
      shell: /usr/local/dos-mitigation/common/setup/jitsi_client_setup.sh
      become: no