- hosts: all
  name: push common files
  tasks:
  - name: push common files
    copy:
      src: "{{ user_dir }}/common"
      dest: "{{ user_dir }}/"
      mode: preserve
    become: yes

- hosts: client
  name: copy puppeteer scripts to home
  tasks:
  - name: copy puppeteer scripts to home
    shell: cp -r {{ user_dir }}/common/puppeteer/ ./
    become: no